ktor:
  application:
    dependencies:
      - com.example.SampleRepository1
      - com.example.Service1
    modules:
      - com.example.ApplicationKt.module
      - com.example.ApplicationKt.module2
  deployment:
    port: 8080
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password